baseURL = 'https://blog.wwyy.love/'
languageCode = 'zh-CN'
title = 'Wang Wei Blog'
theme = "github.com/nodejh/hugo-theme-mini"
defaultContentLanguage = 'zh'
hasCJKLanguage = true
paginate = 3

[permalinks]
posts = "/posts/:title/"

[markup.highlight]
guessSyntax = true
style = "emacs"

[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2

[markup.goldmark.renderer]
unsafe = true

[social]
github = "https://github.com/panghu-00"

[params]
author = "wangwei"
bio = "Software Engineer"
description = "My Blog"
enableRSS = false
enableComments = false
enableGoogleAnalytics = false
showToc = true
showPowerBy = true
math = false
hiddenPostSummaryInHomePage = false
copyright = ""
